name: Nightly Release

on:
  schedule:
    - cron:  '* 0 * * *' # Runs every day at midnight

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: nightly-${{ github.run_number }}
          release_name: Nightly build ${{ github.run_number }}
          draft: false
          prerelease: true
